name: Verify repo is prettier consistent

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build_and_verify:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Set up Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: "23"

            - name: Install dependencies
              run: npm install

            - name: Run prettier in check mode
              run: node_modules/prettier/bin/prettier.cjs . --check
