name: Pull website

on:
    push:
        branches: ["main"]

jobs:
    publish:
        name: Pull the latest commit
        runs-on: ubuntu-latest

        steps:
            - name: Deploy via ssh
              uses: appleboy/ssh-action@v1.2.2
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  port: ${{ secrets.SSH_PORT }}
                  script_stop: true
                  script: |
                      cd /var/www/domains/fnorden.net/
                      sudo -u www-data /usr/bin/git pull
