name: Pull website

on:
    push:
        branches: ["main"]

jobs:
    publish:
        name: Pull the latest commit
        runs-on: ubuntu-latest

        steps:
            - name: Deploy via ssh
              uses: appleboy/ssh-action@v1.2.5
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      set -e
                      nixos-rebuild --switch
